[package]
name = "disk_usage"
version = "0.1.0"
authors = ["Mikkel Schubert <MikkelSch@gmail.com>"]

[dependencies]
clap = { version = "3.0.14", default-features = false, features = [
    "std",
    "suggestions",
] }
libc = "0.2.13"
nix = "0.6.0"
